new algo max_value_less_than_unsorted
KDAB/KDAlgorithms pull request #42
Opened 2023-01-31 10:15 UTC by phyBrackets

2023-02-02 09:51 UTC, ivan-cukic reviewed
Much better, a few nit picks remain

2023-02-02 09:51 UTC, ivan-cukic commented on src/kdalgorithms.h
> +    std::optional<Item> max_value_less_than_unordered(const Container &container, Item &&needle,
I'd make `needle` a `const&` - we don't want to allow the uses to do strange things by changing the needle in their comparison functions.

2023-02-09 13:36 UTC, jesperkdab requested changes
Looks good to me. Please also add min_value_greater_than_unordered

2023-02-13 18:48 UTC, jesperkdab approved these changes

2023-02-13 18:49 UTC, merged